import fs from 'fs';

let dashboardCode = fs.readFileSync('src/pages/Dashboard.tsx', 'utf8');

const missingTop = [
"import React, { useState, useEffect, useRef } from 'react';",
"import { useNavigate } from 'react-router-dom';",
"import { useAuthStore, useSettingsStore } from '../lib/store';",
"import { motion, AnimatePresence } from 'framer-motion';",
"import {",
"  Building2, User, Loader2, Search, MapPin, ChevronRight, MessageSquare,",
"  Clock, PlusCircle, PenTool, CheckCircle2, Shield, Settings,",
"  LogOut, Phone, Mail, FileText, Download, Check, Link, ArrowRight, Wallet, Banknote, HelpCircle,",
"  Briefcase, Activity, Share2, Facebook, Twitter, MessageCircle, Star, X, Eye, EyeOff, LayoutDashboard, Send, Paperclip, AlertCircle, Square, Trash2, Mic, Handshake, Info",
"} from 'lucide-react';",
"import CustomSelect from '../components/CustomSelect';",
"import { io, Socket } from 'socket.io-client';",
"",
"const LOCAL_PAYMENT_METHODS_BY_COUNTRY: Record<string, string[]> = {",
"  'Togo': ['Tmoney', 'Flooz'],",
"  'Bénin': ['MTN Mobile Money', 'Moov Money'],",
"  'Sénégal': ['Orange Money', 'Wave', 'Free Money'],",
"  'Côte d\\'Ivoire': ['Orange Money', 'MTN Mobile Money', 'Moov Money', 'Wave'],",
"  'Burkina Faso': ['Orange Money', 'Moov Money'],",
"  'Mali': ['Orange Money', 'Moov Money'],",
"  'Niger': ['Airtel Money', 'Moov Money'],",
"  'Guinée': ['Orange Money', 'MTN Mobile Money'],",
"  'Cameroun': ['Orange Money', 'MTN Mobile Money'],",
"  'Gabon': ['Airtel Money', 'Moov Money'],",
"  'Congo': ['Airtel Money', 'MTN Mobile Money'],",
"  'République Démocratique du Congo': ['Airtel Money', 'Orange Money', 'M-Pesa', 'Afrimoney']",
"};",
"",
"export default function Dashboard() {",
"  const { user, token, setUser, login, logout } = useAuthStore();",
"  const { settings } = useSettingsStore();",
"  ",
"  const computedWalletBalance = ((user?.referralStats?.totalRevenue || 0) - (user?.referralStats?.transferredRevenue || 0));",
"",
"  const navigate = useNavigate();",
"  const [requests, setRequests] = useState<any[]>([]);",
"  const [toastMessage, setToastMessage] = useState<string | null>(null);",
"  const [loading, setLoading] = useState(true);",
"  const [selectedRequest, setSelectedRequest] = useState<any>(null);",
"  const [isEditProfileOpen, setIsEditProfileOpen] = useState(false);",
"  const [editFormData, setEditFormData] = useState<any>({});",
"  const [isKycLoading, setIsKycLoading] = useState(false);",
"  const [isDeletingAccount, setIsDeletingAccount] = useState(false);",
"  const [isProfDropdownOpen, setIsProfDropdownOpen] = useState(false);",
"",
"  const [activeTab, setActiveTab] = useState('requests');",
"  ",
"  const [showWithdrawModal, setShowWithdrawModal] = useState(false);",
"  const [withdrawAmount, setWithdrawAmount] = useState<number>(0);",
"  const [withdrawMethod, setWithdrawMethod] = useState('');",
"  const [withdrawPhone, setWithdrawPhone] = useState('');",
"  const [isWithdrawing, setIsWithdrawing] = useState(false);",
"",
"  const [showHistoryModal, setShowHistoryModal] = useState(false);",
"  const [walletHistory, setWalletHistory] = useState<any[]>([]);",
"  const [isLoadingHistory, setIsLoadingHistory] = useState(false);",
"",
"  const [showDepositModal, setShowDepositModal] = useState(false);",
"  const [depositAmount, setDepositAmount] = useState<number>(0);",
"  const [depositPlanId, setDepositPlanId] = useState<string>('');",
"  const [depositMethod, setDepositMethod] = useState('');",
"  const [depositPhone, setDepositPhone] = useState('');",
"  const [isDepositing, setIsDepositing] = useState(false);",
"",
"  const [showSubscriptionsModal, setShowSubscriptionsModal] = useState(false);",
"",
"  const [showReviewModal, setShowReviewModal] = useState(false);",
"  const [reviewScore, setReviewScore] = useState(5);",
"  const [reviewComment, setReviewComment] = useState('');",
"  const [isSubmittingReview, setIsSubmittingReview] = useState(false);",
"",
"  const socketRef = useRef<Socket | null>(null);",
"  ",
"  const [replyText, setReplyText] = useState('');",
"  const [replyAudioUrl, setReplyAudioUrl] = useState<string | null>(null);",
"  const [replyAudioData, setReplyAudioData] = useState<string | null>(null);",
"  const [replyAttachmentUrl, setReplyAttachmentUrl] = useState<string | null>(null);",
"  const [isRecordingReply, setIsRecordingReply] = useState(false);",
"  const [isSubmittingReply, setIsSubmittingReply] = useState(false);",
"  const replyMediaRecorderRef = useRef<MediaRecorder | null>(null);",
"",
"  const chatScrollRef = useRef<HTMLDivElement>(null);",
"",
"  useEffect(() => {",
"    if (chatScrollRef.current) {",
"      chatScrollRef.current.scrollTop = chatScrollRef.current.scrollHeight;",
"    }",
"  }, [selectedRequest?.responses]);"
].join('\\n');

const lines = dashboardCode.split('\\n');
lines.shift(); // remove the bad line 1

fs.writeFileSync('src/pages/Dashboard.tsx', missingTop + '\\n' + lines.join('\\n'), 'utf8');
